/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Pnl = IDL.Float64;
export const Status = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
export const TradeType = IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null });
export const Trade = IDL.Record({
  'id' : IDL.Nat,
  'mae' : IDL.Float64,
  'mfe' : IDL.Float64,
  'pnl' : Pnl,
  'status' : Status,
  'currentPrice' : IDL.Float64,
  'asset' : IDL.Text,
  'tradeType' : TradeType,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Float64,
  'entryPrice' : IDL.Float64,
});
export const TradingStats = IDL.Record({
  'tradeCount' : IDL.Nat,
  'avgTradePnl' : Pnl,
  'lossCount' : IDL.Nat,
  'totalPnl' : Pnl,
  'winCount' : IDL.Nat,
  'winRate' : IDL.Float64,
  'netProfit' : Pnl,
  'avgMae' : IDL.Float64,
  'avgMfe' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addTrade' : IDL.Func([Trade], [IDL.Nat], []),
  'closeTrade' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'deleteTrade' : IDL.Func([IDL.Nat], [], []),
  'getAllTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getTrade' : IDL.Func([IDL.Nat], [Trade], ['query']),
  'getTradingStats' : IDL.Func([], [TradingStats], ['query']),
  'getUS10YHistory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'recordUS10YSnapshot' : IDL.Func([IDL.Float64, IDL.Text], [], []),
  'seedSampleTrades' : IDL.Func([], [], []),
  'updateTrade' : IDL.Func([Trade], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Pnl = IDL.Float64;
  const Status = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const TradeType = IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null });
  const Trade = IDL.Record({
    'id' : IDL.Nat,
    'mae' : IDL.Float64,
    'mfe' : IDL.Float64,
    'pnl' : Pnl,
    'status' : Status,
    'currentPrice' : IDL.Float64,
    'asset' : IDL.Text,
    'tradeType' : TradeType,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Float64,
    'entryPrice' : IDL.Float64,
  });
  const TradingStats = IDL.Record({
    'tradeCount' : IDL.Nat,
    'avgTradePnl' : Pnl,
    'lossCount' : IDL.Nat,
    'totalPnl' : Pnl,
    'winCount' : IDL.Nat,
    'winRate' : IDL.Float64,
    'netProfit' : Pnl,
    'avgMae' : IDL.Float64,
    'avgMfe' : IDL.Float64,
  });
  
  return IDL.Service({
    'addTrade' : IDL.Func([Trade], [IDL.Nat], []),
    'closeTrade' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'deleteTrade' : IDL.Func([IDL.Nat], [], []),
    'getAllTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getTrade' : IDL.Func([IDL.Nat], [Trade], ['query']),
    'getTradingStats' : IDL.Func([], [TradingStats], ['query']),
    'getUS10YHistory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'recordUS10YSnapshot' : IDL.Func([IDL.Float64, IDL.Text], [], []),
    'seedSampleTrades' : IDL.Func([], [], []),
    'updateTrade' : IDL.Func([Trade], [], []),
  });
};

export const init = ({ IDL }) => { return []; };