/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Pnl = number;
export type Status = { 'closed' : null } |
  { 'open' : null };
export interface Trade {
  'id' : bigint,
  'mae' : number,
  'mfe' : number,
  'pnl' : Pnl,
  'status' : Status,
  'currentPrice' : number,
  'asset' : string,
  'tradeType' : TradeType,
  'timestamp' : bigint,
  'quantity' : number,
  'entryPrice' : number,
}
export type TradeType = { 'long' : null } |
  { 'short' : null };
export interface TradingStats {
  'tradeCount' : bigint,
  'avgTradePnl' : Pnl,
  'lossCount' : bigint,
  'totalPnl' : Pnl,
  'winCount' : bigint,
  'winRate' : number,
  'netProfit' : Pnl,
  'avgMae' : number,
  'avgMfe' : number,
}
export interface _SERVICE {
  'addTrade' : ActorMethod<[Trade], bigint>,
  'closeTrade' : ActorMethod<[bigint, number], undefined>,
  'deleteTrade' : ActorMethod<[bigint], undefined>,
  'getAllTrades' : ActorMethod<[], Array<Trade>>,
  'getTrade' : ActorMethod<[bigint], Trade>,
  'getTradingStats' : ActorMethod<[], TradingStats>,
  /**
   * / Returns all stored US10Y snapshots sorted by dateLabel ascending (oldest first).
   */
  'getUS10YHistory' : ActorMethod<[], Array<[string, number]>>,
  /**
   * / Records a US10Y yield snapshot for a given date label (e.g. "2026-04-08").
   * / Overwrites any existing value for that date, then trims to the last 30 entries.
   */
  'recordUS10YSnapshot' : ActorMethod<[number, string], undefined>,
  'seedSampleTrades' : ActorMethod<[], undefined>,
  'updateTrade' : ActorMethod<[Trade], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];