/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TradingStats {
    tradeCount: bigint;
    avgTradePnl: Pnl;
    lossCount: bigint;
    totalPnl: Pnl;
    winCount: bigint;
    winRate: number;
    netProfit: Pnl;
    avgMae: number;
    avgMfe: number;
}
export type Pnl = number;
export interface Trade {
    id: bigint;
    mae: number;
    mfe: number;
    pnl: Pnl;
    status: Status;
    currentPrice: number;
    asset: string;
    tradeType: TradeType;
    timestamp: bigint;
    quantity: number;
    entryPrice: number;
}
export enum Status {
    closed = "closed",
    open = "open"
}
export enum TradeType {
    long_ = "long",
    short_ = "short"
}
export interface backendInterface {
    addTrade(trade: Trade): Promise<bigint>;
    closeTrade(id: bigint, finalPrice: number): Promise<void>;
    deleteTrade(id: bigint): Promise<void>;
    getAllTrades(): Promise<Array<Trade>>;
    getTrade(id: bigint): Promise<Trade>;
    getTradingStats(): Promise<TradingStats>;
    /**
     * / Returns all stored US10Y snapshots sorted by dateLabel ascending (oldest first).
     */
    getUS10YHistory(): Promise<Array<[string, number]>>;
    /**
     * / Records a US10Y yield snapshot for a given date label (e.g. "2026-04-08").
     * / Overwrites any existing value for that date, then trims to the last 30 entries.
     */
    recordUS10YSnapshot(value: number, dateLabel: string): Promise<void>;
    seedSampleTrades(): Promise<void>;
    updateTrade(trade: Trade): Promise<void>;
}
import type { Pnl as _Pnl, Status as _Status, Trade as _Trade, TradeType as _TradeType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTrade(arg0: Trade): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrade(to_candid_Trade_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrade(to_candid_Trade_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async closeTrade(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeTrade(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeTrade(arg0, arg1);
            return result;
        }
    }
    async deleteTrade(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrade(arg0);
            return result;
        }
    }
    async getAllTrades(): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrades();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrades();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrade(arg0: bigint): Promise<Trade> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrade(arg0);
                return from_candid_Trade_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrade(arg0);
            return from_candid_Trade_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradingStats(): Promise<TradingStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradingStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradingStats();
            return result;
        }
    }
    async getUS10YHistory(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUS10YHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUS10YHistory();
            return result;
        }
    }
    async recordUS10YSnapshot(arg0: number, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordUS10YSnapshot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordUS10YSnapshot(arg0, arg1);
            return result;
        }
    }
    async seedSampleTrades(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleTrades();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleTrades();
            return result;
        }
    }
    async updateTrade(arg0: Trade): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrade(to_candid_Trade_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrade(to_candid_Trade_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Status_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TradeType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeType): TradeType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    mae: number;
    mfe: number;
    pnl: _Pnl;
    status: _Status;
    currentPrice: number;
    asset: string;
    tradeType: _TradeType;
    timestamp: bigint;
    quantity: number;
    entryPrice: number;
}): {
    id: bigint;
    mae: number;
    mfe: number;
    pnl: Pnl;
    status: Status;
    currentPrice: number;
    asset: string;
    tradeType: TradeType;
    timestamp: bigint;
    quantity: number;
    entryPrice: number;
} {
    return {
        id: value.id,
        mae: value.mae,
        mfe: value.mfe,
        pnl: value.pnl,
        status: from_candid_Status_n10(_uploadFile, _downloadFile, value.status),
        currentPrice: value.currentPrice,
        asset: value.asset,
        tradeType: from_candid_TradeType_n12(_uploadFile, _downloadFile, value.tradeType),
        timestamp: value.timestamp,
        quantity: value.quantity,
        entryPrice: value.entryPrice
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
}): Status {
    return "closed" in value ? Status.closed : "open" in value ? Status.open : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    long: null;
} | {
    short: null;
}): TradeType {
    return "long" in value ? TradeType.long : "short" in value ? TradeType.short : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Array<Trade> {
    return value.map((x)=>from_candid_Trade_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Status_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TradeType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): _TradeType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Trade_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trade): _Trade {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    mae: number;
    mfe: number;
    pnl: Pnl;
    status: Status;
    currentPrice: number;
    asset: string;
    tradeType: TradeType;
    timestamp: bigint;
    quantity: number;
    entryPrice: number;
}): {
    id: bigint;
    mae: number;
    mfe: number;
    pnl: _Pnl;
    status: _Status;
    currentPrice: number;
    asset: string;
    tradeType: _TradeType;
    timestamp: bigint;
    quantity: number;
    entryPrice: number;
} {
    return {
        id: value.id,
        mae: value.mae,
        mfe: value.mfe,
        pnl: value.pnl,
        status: to_candid_Status_n3(_uploadFile, _downloadFile, value.status),
        currentPrice: value.currentPrice,
        asset: value.asset,
        tradeType: to_candid_TradeType_n5(_uploadFile, _downloadFile, value.tradeType),
        timestamp: value.timestamp,
        quantity: value.quantity,
        entryPrice: value.entryPrice
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    closed: null;
} | {
    open: null;
} {
    return value == Status.closed ? {
        closed: null
    } : value == Status.open ? {
        open: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): {
    long: null;
} | {
    short: null;
} {
    return value == TradeType.long ? {
        long_: null
    } : value == TradeType.short ? {
        short_: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
